### ISSUE TITLE
AWS -> Azure plan

### ISSUE THREAD

**Issue by marcoacierno** [pythonitalia/pycon#3640]
WIP & High-level Plan to keep track of it.

Azure region: Milan

# Pre migration

- [x] Move away from microservices (#3594 #3580 #3575 #3573 #3583)
- [x] Move away from SQS to Celery (#3628)
- [ ] Setup a new Terraform project for Azure
- [ ] Decide how we are going to deploy the BE and Pretix:
	- [ ] App Service
	- [ ] Azure VMs + AWS ECS Anywhere
- [ ] Setup a Storage account
- [ ] Look into Encryption / DIsk encryption and similar for GDPR
- [ ] Plan how we are going to copy the data from S3 to Azure.
	- [ ] Evaluate if we should keep using S3 for now
- [ ] Check if Azure has a SES equivalent now
	- [ ] Evaluate if we should keep using SES for now
- [ ] Deploy a Postgres instance
- [ ] Deploy a Redis instance
- [ ] Run some load testing to understand our limits

# Go-live

To do around 1 am to 3m GMT (2 am to 4 am CET)

- [ ] Set PyCon in read-only mode (can we set the DB to not allow writes?)
- [ ] Migrate DB data into the Azure DB
	- [ ] Does it make sense to point AWS to the Azure DB so that requests going to AWS get handled?
	- [ ] Do we set Azure DB as a replication DB to do the copy? How does it work given they are in VPC?

# Nice-to-have

- [ ] Move Pretix assets to Storage instead of relying on them being in the VM, to avoid CSS-style outages :)

VM migration: https://learn.microsoft.com/en-us/azure/migrate/tutorial-migrate-aws-virtual-machines (probably for pretix)

```[tasklist]
### Tasks
- [ ] https://github.com/pythonitalia/pycon/pull/3628
```
