### ISSUE TITLE
Migrate SQS tasks to Celery

### ISSUE THREAD

**Issue by marcoacierno** [pythonitalia/pycon#3643]
We merged #3628 now and need to migrate everything we do in `domain_events` to celery:

```[tasklist]
### Tasks
- [x] Migrate vercel invalidation to celery
- [ ] https://github.com/pythonitalia/pycon/issues/3644
- [ ] https://github.com/pythonitalia/pycon/issues/3645
- [ ] https://github.com/pythonitalia/pycon/issues/3646
- [ ] https://github.com/pythonitalia/pycon/issues/3647
- [ ] https://github.com/pythonitalia/pycon/issues/3648
- [ ] https://github.com/pythonitalia/pycon/issues/3649
- [ ] https://github.com/pythonitalia/pycon/issues/3650
- [x] New Plain email chat
- [ ] https://github.com/pythonitalia/pycon/issues/3656
- [ ] https://github.com/pythonitalia/pycon/issues/3657
- [ ] https://github.com/pythonitalia/pycon/issues/3658
- [ ] https://github.com/pythonitalia/pycon/issues/3659
- [ ] https://github.com/pythonitalia/pycon/issues/3661
- [x] Volunteers Push notification
- [ ] https://github.com/pythonitalia/pycon/issues/3660
```
