### ISSUE TITLE
Migrate off Vercel and to OpenNext/AWS

### ISSUE THREAD

**Issue by marcoacierno** [pythonitalia/pycon#3853]
```[tasklist]
### Tasks
- [ ] Confirm https://open-next.js.org/ is the best option (Support for ISG / Server-side rendered pages and @vercel/og?)
- [ ] Confirm AWS costs and how the infrastructure will be setup - Using https://sst.dev/? I would prefer terraform if SST is just an alternative to terraform
- [ ] Remove vercel banner from the website footer
- [ ] Remove vercel banner from the readme repo
```

We also use vercel for https://github.com/pythonitalia/community BE, FE and the Postgres database are all in Vercel. It requires a bigger migration. We might consider moving it into this BE.

**Comment by marcoacierno** [comment]
While it has some shortcomings, AWS amplify might be a good alternative too: https://aws.amazon.com/amplify/

Pricing-wise I am not sure convinced: https://aws.amazon.com/amplify/pricing/

**Comment by patrick91** [comment]
I'm still waiting to hear from Vercel if we can keep the sponsorship 😊

**Comment by marcoacierno** [comment]
We ended up migrating to ECS for Production and still use Vercel for PR previews
