### ISSUE TITLE
Allow users to change their profile email

### ISSUE THREAD

**Issue by marcoacierno** [pythonitalia/pycon#3897]
We should allow users to change the email of their account via UI, without having to contact us via email.

```[tasklist]
### Tasks
- [ ] Add verify email flow
- [ ] Add banner in UI asking people to verify their current email address
- [ ] Implement endpoint to trigger the email change
- [ ] Implement UI to change the email address
- [ ] Implement endpoint to confirm the email change, update the user email and orders to match their new email (?)
```
