### ISSUE TITLE
Deployment improvements

### ISSUE THREAD

**Issue by marcoacierno** [pythonitalia/pycon#3900]
Improvements:

```[tasklist]
### Tasks
- [ ] Speed up the deployment time. Currently from start to finish it takes 8 mins
- [ ] Remove the need to build both an ARM and non-ARM version of the BE. Migrate everything BE related to use ARM
- [ ] Look into alternatives to our current Hetzner machine that builds the ARM machine
```

# Alternatives to Hetzner

Maybe we can find a SaaS that offers ARM GitHub runners? We could also investigate a way to automatically start a more powerful Hetzner machine, register it as runner and have the ARM build run there. 

Fargate could be an option too (and involves less work to automatically start the machine), pricer than Hetzner (4 vCPU and 8GB  RAM costs $0.227USD) but it is included in our credits balance so won't be an extra expense.
