### ISSUE TITLE
Convert all emails to the new email template system

### ISSUE THREAD

**Issue by marcoacierno** [pythonitalia/pycon#4074]
- [x] Proposal rejected - #4073
- [x] GRANT_APPROVED #4080
- [x] GRANT_WAITING_LIST #4081
- [x] GRANT_WAITING_LIST_UPDATE #4081
- [x] GRANT_VOUCHER_CODE - TODO This should be merged to the new Conference voucher system #4085
- [x] GRANT_REJECTED - #4078
- [x] RESET_PASSWORD #4083
- [x] SUBMISSION_IN_WAITING_LIST #4075
- [x] SUBMISSION_SCHEDULE_TIME_CHANGED #4076
- [x] SPEAKER_COMMUNICATION #4084
